import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__name__), '.env'))

class Config:
    FLASK_APP = os.environ.get('FLASK_APP')
    FLASK_ENV = os.environ.get('FLASK_ENV')
    SECRET_KEY = os.environ.get('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
    BT_MERCHANT_ID = os.environ.get('BT_MERCHANT_ID')
    BT_MERCHANT_ACCOUNT_ID = os.environ.get('BT_MERCHANT_ACCOUNT_ID')
    BT_PUBLIC_KEY = os.environ.get('BT_PUBLIC_KEY')
    BT_PRIVATE_KEY = os.environ.get('BT_PRIVATE_KEY')
    MAIL_SERVER = os.environ.get('MAIL_SERVER')
    MAIL_PORT = os.environ.get('MAIL_PORT')
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS')
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    PRODUCTS_PER_PAGE = int(os.environ.get('PRODUCTS_PER_PAGE'))
    CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME')
    CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY')
    CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET')
    CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL')
    MAILCHIMP_API_HEADER = os.environ.get('MAILCHIMP_API_HEADER')
    MAILCHIMP_URL = os.environ.get('MAILCHIMP_URL')
    MAILCHIMP_MAIL_ID = os.environ.get('MAILCHIMP_MAIL_ID')
    MAILCHIMP_USERNAME = os.environ.get('MAILCHIMP_USERNAME')
    MAILCHIMP_API_KEY = os.environ.get('MAILCHIMP_API_KEY')
    # FLASK_ADMIN_SWATCH = os.getenv('FLASK_ADMIN_SWATCH')