version: '3.9'
services:
  web:
    image: zaraconsulting/comececeme:latest

    container_name: comececeme

    build: 
      context: ./

      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "5001:5000"

    run:
      web: exec gunicorn app:create_app()