"""empty message

Revision ID: 04c34ce99e89
Revises: eefcd38dbb8a
Create Date: 2020-09-24 17:55:43.733832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c34ce99e89'
down_revision = 'eefcd38dbb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'bundle_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('bundle_length', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
