"""removed discount and discount_price column from Product model

Revision ID: 0e86a484b2f7
Revises: 881c29e4d8b0
Create Date: 2021-11-06 16:56:23.969739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e86a484b2f7'
down_revision = '881c29e4d8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    op.drop_column('product', 'discount_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('discount', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
