"""added HairCategory,image column

Revision ID: 128525095a5a
Revises: 4b93758877ea
Create Date: 2021-10-19 22:09:22.391792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128525095a5a'
down_revision = '4b93758877ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'image')
    # ### end Alembic commands ###
