"""tried to fix hair models

Revision ID: 131d1e694d67
Revises: 5a1cdf4cd0d9
Create Date: 2020-08-27 23:45:34.588948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131d1e694d67'
down_revision = '5a1cdf4cd0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hair', 'hair_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hair', type_='foreignkey')
    op.drop_column('hair', 'category_id')
    # ### end Alembic commands ###
