"""added relationship between Pattern and Hair

Revision ID: 1886cd29698d
Revises: 201bad355669
Create Date: 2020-08-29 13:22:13.742760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1886cd29698d'
down_revision = '201bad355669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('pattern_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hair', 'pattern', ['pattern_id'], ['id'])
    op.drop_constraint('pattern_hair_id_fkey', 'pattern', type_='foreignkey')
    op.drop_column('pattern', 'hair_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern', sa.Column('hair_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pattern_hair_id_fkey', 'pattern', 'hair', ['hair_id'], ['id'])
    op.drop_constraint(None, 'hair', type_='foreignkey')
    op.drop_column('hair', 'pattern_id')
    # ### end Alembic commands ###
