"""added image columns to HairCategory

Revision ID: 1bac1c51c6ca
Revises: 131d1e694d67
Create Date: 2020-08-29 00:17:11.295922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bac1c51c6ca'
down_revision = '131d1e694d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'image')
    # ### end Alembic commands ###
