"""empty message

Revision ID: 1f83e310dbfb
Revises: 34a3c9057783
Create Date: 2020-06-06 01:24:09.353249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f83e310dbfb'
down_revision = '34a3c9057783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.id'], name='cart_customerId_fkey'),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name='cart_productId_fkey')
    )
    # ### end Alembic commands ###
