"""empty message

Revision ID: 201bad355669
Revises: cb5f94a615eb
Create Date: 2020-08-29 04:30:04.499468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201bad355669'
down_revision = 'cb5f94a615eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('hair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hair_id'], ['hair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern')
    # ### end Alembic commands ###
