"""empty message

Revision ID: 266219bb21e7
Revises: ef97ccd20ae6
Create Date: 2021-11-08 18:43:53.545480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266219bb21e7'
down_revision = 'ef97ccd20ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('beauty_product_id', sa.Integer(), nullable=True))
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'cart', 'product', ['beauty_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cart', 'beauty_product_id')
    # ### end Alembic commands ###
