"""empty message

Revision ID: 3613b8d53bbe
Revises: cadb3d7403cb
Create Date: 2021-08-25 17:44:11.653491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3613b8d53bbe'
down_revision = 'cadb3d7403cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern', 'display_name')
    # ### end Alembic commands ###
