"""empty message

Revision ID: 387191b16ac4
Revises: 92f9ff92f553
Create Date: 2020-06-05 19:41:15.521837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387191b16ac4'
down_revision = '92f9ff92f553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_productId_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_customerId_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    op.drop_column('cart', 'customerId')
    op.drop_column('cart', 'productId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_customerId_fkey', 'cart', 'customer', ['customerId'], ['id'])
    op.create_foreign_key('cart_productId_fkey', 'cart', 'product', ['productId'], ['id'])
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'customer_id')
    # ### end Alembic commands ###
