"""empty message

Revision ID: 3e1ea870ccc3
Revises: 82633186f46c
Create Date: 2020-06-07 10:48:35.658077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1ea870ccc3'
down_revision = '82633186f46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'order_id')
    # ### end Alembic commands ###
