"""empty message

Revision ID: 4a8232a3bf2d
Revises: 771b62bc832a
Create Date: 2021-11-06 14:44:20.387311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8232a3bf2d'
down_revision = '771b62bc832a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('is_wig', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'is_wig')
    # ### end Alembic commands ###
