"""added support for wig products

Revision ID: 4b93758877ea
Revises: 5a3bb9a23002
Create Date: 2021-10-19 10:15:59.744193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b93758877ea'
down_revision = '5a3bb9a23002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('name', sa.String(), nullable=True))
    op.add_column('hair', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('hair_category', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hair', 'image')
    op.drop_column('hair', 'name')
    # ### end Alembic commands ###
