"""created Hair models

Revision ID: 52e0ecee1756
Revises: 2b1acd6c1008
Create Date: 2020-08-27 17:33:06.339884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e0ecee1756'
down_revision = '2b1acd6c1008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'wave_pattern')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('wave_pattern', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
