"""changed the car class to take hair products

Revision ID: 588096233bb5
Revises: f99270f72e83
Create Date: 2020-09-01 06:20:20.157122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588096233bb5'
down_revision = 'f99270f72e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('cart_hair_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'hair', ['product_id'], ['id'])
    op.drop_column('cart', 'hair_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('hair_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_hair_id_fkey', 'cart', 'hair', ['hair_id'], ['id'])
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###
