"""empty message

Revision ID: 5a1cdf4cd0d9
Revises: 52e0ecee1756
Create Date: 2020-08-27 23:17:47.628201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1cdf4cd0d9'
down_revision = '52e0ecee1756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hair_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hair_category')
    op.drop_table('hair')
    # ### end Alembic commands ###
