"""empty message

Revision ID: 5a3bb9a23002
Revises: f8ed95f3d14c
Create Date: 2021-10-19 00:00:00.893185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3bb9a23002'
down_revision = 'f8ed95f3d14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'name')
    # ### end Alembic commands ###
