"""empty message

Revision ID: 5c12a920dc4a
Revises: a0e024fccb4d
Create Date: 2020-06-04 00:12:07.984811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c12a920dc4a'
down_revision = 'a0e024fccb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], ),
    sa.PrimaryKeyConstraint('customerId', 'productId')
    )
    op.drop_column('cart_item', 'quantity')
    op.add_column('product_review', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_review', 'email')
    op.add_column('cart_item', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('cart')
    # ### end Alembic commands ###
