"""added rank column to Role model

Revision ID: 6091c653359a
Revises: 67e12aac8873
Create Date: 2020-09-24 21:57:23.211559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6091c653359a'
down_revision = '67e12aac8873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'rank')
    # ### end Alembic commands ###
