"""added description column to HairCategory

Revision ID: 67cb1822c451
Revises: 1886cd29698d
Create Date: 2020-08-29 17:04:48.303947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cb1822c451'
down_revision = '1886cd29698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'description')
    # ### end Alembic commands ###
