"""empty message

Revision ID: 67e12aac8873
Revises: 04c34ce99e89
Create Date: 2020-09-24 18:03:00.723459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e12aac8873'
down_revision = '04c34ce99e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('bundle_length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'bundle_length')
    # ### end Alembic commands ###
