"""added first_name and last_name columns to Account model

Revision ID: 691cd63b385d
Revises: a935515e3c1c
Create Date: 2020-09-23 11:38:36.052436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691cd63b385d'
down_revision = 'a935515e3c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('account', sa.Column('last_name', sa.String(), nullable=True))
    op.alter_column('account', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('account', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'account', ['last_name'])
    op.create_unique_constraint(None, 'account', ['first_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.alter_column('account', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('account', 'last_name')
    op.drop_column('account', 'first_name')
    # ### end Alembic commands ###
