"""added is_viewable and in_stock columns to Product model

Revision ID: 6df3735dbaf2
Revises: 8b1a507f7f21
Create Date: 2021-11-08 03:30:09.197989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df3735dbaf2'
down_revision = '8b1a507f7f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_viewable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_viewable')
    # ### end Alembic commands ###
