"""empty message

Revision ID: 76c3c6fb657c
Revises: 266219bb21e7
Create Date: 2021-11-08 19:49:13.767613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c3c6fb657c'
down_revision = '266219bb21e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('beauty_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'product', ['beauty_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'beauty_product_id')
    # ### end Alembic commands ###
