"""empty message

Revision ID: 771b62bc832a
Revises: a9ea55427e3d
Create Date: 2021-10-31 11:43:09.971737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771b62bc832a'
down_revision = 'a9ea55427e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('is_wig', sa.Boolean(), nullable=True))
    op.drop_column('hair', 'is_wigs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('is_wigs', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hair', 'is_wig')
    # ### end Alembic commands ###
