"""empty message

Revision ID: 7d5703fb9531
Revises: d48eeec468f9
Create Date: 2021-11-08 18:34:32.731269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5703fb9531'
down_revision = 'd48eeec468f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('cart_beauty_product_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'beauty_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('beauty_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_beauty_product_id_fkey', 'cart', 'product', ['beauty_product_id'], ['id'])
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
