"""empty message

Revision ID: 7fa4daaf0886
Revises: 6df3735dbaf2
Create Date: 2021-11-08 18:15:53.458421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa4daaf0886'
down_revision = '6df3735dbaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('beauty_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'product', ['beauty_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'beauty_product_id')
    # ### end Alembic commands ###
