"""empty message

Revision ID: 81650c73011c
Revises: 52aa0ab1f7f5
Create Date: 2020-05-26 00:32:26.021826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81650c73011c'
down_revision = '52aa0ab1f7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service', sa.Column('description', sa.String(), nullable=True))
    op.add_column('service', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('service', 'author')
    op.drop_column('service', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'title')
    op.drop_column('service', 'description')
    op.drop_table('service_category')
    # ### end Alembic commands ###
