"""empty message

Revision ID: 81855f40c65a
Revises: fa6730ecfb1a
Create Date: 2020-06-05 18:46:44.137511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81855f40c65a'
down_revision = 'fa6730ecfb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'quantity')
    op.create_unique_constraint(None, 'customer', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
