"""empty message

Revision ID: 82b469b1c89e
Revises: 3e1ea870ccc3
Create Date: 2020-06-07 11:15:00.202506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b469b1c89e'
down_revision = '3e1ea870ccc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
