"""empty message

Revision ID: 89a0e8f05821
Revises: 128525095a5a
Create Date: 2021-10-20 00:31:40.327700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a0e8f05821'
down_revision = '128525095a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'image')
    # ### end Alembic commands ###
