"""empty message

Revision ID: 8c4008b33181
Revises: 7e7b0cf8fc7e
Create Date: 2020-09-02 12:36:10.797046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4008b33181'
down_revision = '7e7b0cf8fc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('bundle_length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'bundle_length')
    # ### end Alembic commands ###
