"""added is_customer column to customer model

Revision ID: 95c36909c5c0
Revises: 049dbbe05a11
Create Date: 2020-09-28 23:25:26.501499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c36909c5c0'
down_revision = '049dbbe05a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_customer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_customer')
    # ### end Alembic commands ###
