"""added coupon model

Revision ID: 979a876ec756
Revises: 6f2270ab8d95
Create Date: 2020-09-21 02:29:34.363981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979a876ec756'
down_revision = '6f2270ab8d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'coupon', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'coupon_id')
    op.drop_table('coupon')
    # ### end Alembic commands ###
