"""empty message

Revision ID: a22f9c92c517
Revises: 20f9cd2dd05a
Create Date: 2020-08-19 01:05:30.100535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22f9c92c517'
down_revision = '20f9cd2dd05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'length')
    # ### end Alembic commands ###
