"""empty message

Revision ID: a3db5ba43591
Revises: c04ac039f43e
Create Date: 2020-06-07 18:35:27.967746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3db5ba43591'
down_revision = 'c04ac039f43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_cart_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_cart_id_fkey', 'order', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###
