"""empty message

Revision ID: a5947406ba14
Revises: 387191b16ac4
Create Date: 2020-06-06 01:02:08.456555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5947406ba14'
down_revision = '387191b16ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('customerId', sa.Integer(), nullable=False))
    op.add_column('cart', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('cart', sa.Column('productId', sa.Integer(), nullable=False))
    op.add_column('cart', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_constraint('cart_customer_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'product', ['productId'], ['id'])
    op.create_foreign_key(None, 'cart', 'customer', ['customerId'], ['id'])
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'product', ['product_id'], ['id'])
    op.create_foreign_key('cart_customer_id_fkey', 'cart', 'customer', ['customer_id'], ['id'])
    op.drop_column('cart', 'quantity')
    op.drop_column('cart', 'productId')
    op.drop_column('cart', 'id')
    op.drop_column('cart', 'customerId')
    # ### end Alembic commands ###
