"""empty message

Revision ID: a9ea55427e3d
Revises: 89a0e8f05821
Create Date: 2021-10-31 11:35:43.749285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ea55427e3d'
down_revision = '89a0e8f05821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('is_wigs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair', 'is_wigs')
    # ### end Alembic commands ###
