"""empty message

Revision ID: afc254c3014a
Revises: 4907e517c328
Create Date: 2020-05-29 17:20:26.176435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc254c3014a'
down_revision = '4907e517c328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_name_key', 'cart_item', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_item_name_key', 'cart_item', ['name'])
    # ### end Alembic commands ###
