"""empty message

Revision ID: c04ac039f43e
Revises: 82b469b1c89e
Create Date: 2020-06-07 18:33:41.601161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04ac039f43e'
down_revision = '82b469b1c89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###
