"""added image column to HairCategory

Revision ID: c2bafbcae2a0
Revises: 67cb1822c451
Create Date: 2020-08-30 05:01:40.204353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bafbcae2a0'
down_revision = '67cb1822c451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'image')
    # ### end Alembic commands ###
