"""empty message

Revision ID: cadb3d7403cb
Revises: 9ae59c03100b
Create Date: 2021-08-25 17:37:25.303490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadb3d7403cb'
down_revision = '9ae59c03100b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_category', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hair_category', 'display_name')
    # ### end Alembic commands ###
