"""Added is_viewable column to Pattern class

Revision ID: d970b2cf54bf
Revises: 3613b8d53bbe
Create Date: 2021-10-16 18:46:52.284892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd970b2cf54bf'
down_revision = '3613b8d53bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern', sa.Column('is_viewable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern', 'is_viewable')
    # ### end Alembic commands ###
