"""removed unique column constraint on Account model

Revision ID: eefcd38dbb8a
Revises: 691cd63b385d
Create Date: 2020-09-24 12:50:13.065723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefcd38dbb8a'
down_revision = '691cd63b385d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_first_name_key', 'account', type_='unique')
    op.drop_constraint('account_last_name_key', 'account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('account_last_name_key', 'account', ['last_name'])
    op.create_unique_constraint('account_first_name_key', 'account', ['first_name'])
    # ### end Alembic commands ###
