"""empty message

Revision ID: fbe661a70814
Revises: 5875e994e0d5
Create Date: 2021-10-18 19:59:46.924076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe661a70814'
down_revision = '5875e994e0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair', sa.Column('is_viewable', sa.Boolean(), nullable=True))
    op.add_column('hair_category', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('pattern', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern', 'display_name')
    op.drop_column('hair_category', 'display_name')
    op.drop_column('hair', 'is_viewable')
    # ### end Alembic commands ###
