"""empty message

Revision ID: fd10ecd0eebf
Revises: a22f9c92c517
Create Date: 2020-08-23 22:42:56.685265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd10ecd0eebf'
down_revision = 'a22f9c92c517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_category', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_category', 'tag')
    # ### end Alembic commands ###
